#!/bin/sh -e
echo "--- Syncing Environment (Root) ---"
uv sync
echo "--- Checking README Sync ---"
./scripts/sync-readmes --check


echo "=== Checking PyWire (Core) ==="
(cd pywire && ./scripts/check)

echo "=== Checking PyWire Language Server ==="
(cd pywire-language-server && ./scripts/check)

echo "=== Checking Create PyWire App ==="
(cd create-pywire-app && ./scripts/check)

echo "=== Checking Examples ==="
(cd examples && ./scripts/check)
